[package]
name = "install_a_bot"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33.3"
toml = "0.5.8"
# Keep curl and openssl static to support our "download binary and good to go" approach
curl = { version = "0.4.38", features = ["static-curl", "static-ssl"] }