[systemconfig]
install_cmd = "apt --yes install"

# Following are examples of user defined targets
[general]
install_cmd = "apt --yes install"
packages = ["cmake", "git", "gitkraken"]

[packagedefinition.gitkraken]
source="local"
url="/home/username/codium-1.60.2-1632356608.el7.x86_64.rpm"

[packagedefinition.codium]
source="web"
url="127.0.0.1:8000/codium-1.60.2-1632356608.el7.x86_64.rpm"